version: '3.8'

services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: skypro_l29
      POSTGRES_PASSWORD: skypro_l29
      POSTGRES_DB: skypro_l29
    restart: always
    ports:
    - "5431:5432"

volumes:
  postgres_data:
